#!/bin/sh

cd ./prjlinux




echo "================ compiling umsconfig for linux debug ================"
make -j4 -f makefile_linux clean debug 1>umsconfig_linux_compile_debug.txt 2>&1
mv umsconfig_linux_compile_debug.txt ../../../10-common/version/compileinfo/ -f

echo "================ compiling umsconfig for linux release ================"
make -j4 -f makefile_linux clean release 1>umsconfig_linux_compile_release.txt 2>&1
mv umsconfig_linux_compile_release.txt ../../../10-common/version/compileinfo/ -f


cd ../../
