#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = test_config
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/om2.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/om2.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Manifest.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Manifest.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/BuildEnvironment.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/elf/TMS470.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/elf/TMS470.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/io/File.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/io/File.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/IPackage.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/IPackage.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/arm/GCArmv6.xs
package.mak: package.bld
/mnt/hgfs/D/code/20131028_TPS/Professional_VOB/10-common/common/linux_compile/config.bld:
package.mak: /mnt/hgfs/D/code/20131028_TPS/Professional_VOB/10-common/common/linux_compile/config.bld
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Utils.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Utils.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/xmlgen.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/xmlgen.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/bld.js:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/bld.js
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/io/package.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/io/package.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/Linux86.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/Linux86.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/package.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/package.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/PackageContents.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/PackageContents.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/template.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/template.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/include/utils.tci:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/include/utils.tci
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/xdc.tci:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/xdc.tci
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Script.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Script.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/ITarget.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/ITarget.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/global/Clock.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/global/Clock.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/package.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/package.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/Mingw.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/Mingw.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/ITarget.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/ITarget.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/MVArm9.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/MVArm9.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Executable.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Executable.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/package.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/package.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/elf/ITarget.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/elf/ITarget.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/elf/package.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/ti/targets/elf/package.xs
package.mak: config.bld
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/UCArm9.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/UCArm9.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/xmlgen2.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/xmlgen2.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Library.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Library.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Repository.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/Repository.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/ITarget.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/ITarget.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/arm/GCArmv7A.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/tools/configuro/template/compiler.opt.xdt
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/_gen.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/_gen.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/ITargetFilter.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/ITargetFilter.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/package.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/bld/package.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/global/Trace.xs:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/services/global/Trace.xs
/opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/xdc/tools/configuro/template/package.xs.xdt
endif

gnu.targets.arm.GCArmv7A.rootDir ?= /opt/CodeSourcery/Sourcery_G++_Lite//
gnu.targets.arm.packageBase ?= /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.ov7A
.PHONY: all,v7A .dlls,v7A .executables,v7A test,v7A
all,v7A: .executables,v7A
.executables,v7A: .libraries,v7A
.executables,v7A: .dlls,v7A
.dlls,v7A: .libraries,v7A
.libraries,v7A: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,v7A
	@$(ECHO) xdc .executables,v7A
	@$(ECHO) xdc .libraries,v7A
	@$(ECHO) xdc .dlls,v7A


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_test_config.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package test_config" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,v7A .executables: 81xxApp.xv7A

-include package/cfg/81xxApp_xv7A.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/81xxApp_xv7A.dep
endif
package/cfg/81xxApp_xv7A.ov7A : | package/cfg/81xxApp_xv7A.xdl
81xxApp.xv7A:
	$(RM) $@
	@$(MSG) lnkv7A $@ ...
	$(RM) $(XDCCFGDIR)$@.map
	$(gnu.targets.arm.GCArmv7A.rootDir)/bin/arm-none-linux-gnueabi-gcc    -o $@ package/cfg/81xxApp_xv7A.ov7A -Wl,-T,package/cfg/81xxApp_xv7A.xdl   -Wl,-Map=$(XDCCFGDIR)/$@.map -lstdc++ -L$(gnu.targets.arm.GCArmv7A.rootDir)/arm-none-linux-gnueabi/lib
	
81xxApp.xv7A:LD_LIBRARY_PATH=


ifeq (,$(wildcard .libraries,v7A))
81xxApp.xv7A package/cfg/81xxApp_xv7A.c: .libraries,v7A
endif

package/cfg/81xxApp_xv7A.c package/cfg/81xxApp_xv7A.h package/cfg/81xxApp_xv7A.xdl: override _PROG_NAME := 81xxApp.xv7A
package/cfg/81xxApp_xv7A.c: package/cfg/81xxApp_xv7A.cfg
81xxApp.test test,v7A test: 81xxApp.xv7A.test

81xxApp.xv7A.test:: 81xxApp.xv7A
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 81xxApp.xv7A.test
else
	@$(MSG) running $<  ...
	$(call EXEC.81xxApp.xv7A, ) 
endif


clean:: clean,v7A
	-$(RM) package/cfg/81xxApp_xv7A.cfg
	-$(RM) package/cfg/81xxApp_xv7A.dep
	-$(RM) package/cfg/81xxApp_xv7A.c
	-$(RM) package/cfg/81xxApp_xv7A.xdc.inc

clean,v7A::
	-$(RM) 81xxApp.xv7A
	-$(RM) .tmp,81xxApp.xv7A,*

%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
81xxApp_xv7A.ov7A,copy : package/cfg/81xxApp_xv7A.ov7A
81xxApp_xv7A.sv7A,copy : package/cfg/81xxApp_xv7A.sv7A

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,test_config
test_config.tar: package/build.cfg
test_config.tar: package/package.ext.xml
test_config.tar: package/package.xdc.inc
test_config.tar: package/package.bld.xml
test_config.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/test_config.tar.dep
endif
package/rel/test_config/test_config/package/package.rel.xml:

test_config.tar: package/rel/test_config.xdc.inc package/rel/test_config/test_config/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/test_config.xdc.inc,package/rel/test_config.tar.dep)


release release,test_config: all test_config.tar
clean:: .clean
	-$(RM) test_config.tar
	-$(RM) package/rel/test_config.xdc.inc
	-$(RM) package/rel/test_config.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
