// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

#ifndef PROTOBUF_enum_2eproto__INCLUDED
#define PROTOBUF_enum_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace pbmsg {

// Internal implementation detail -- do not call these.
void PROTOBUFMSG_API protobuf_AddDesc_enum_2eproto();
void protobuf_AssignDesc_enum_2eproto();
void protobuf_ShutdownFile_enum_2eproto();


enum EmViewType {
  emViewType_Invalid = 0,
  emViewType_Ep = 1,
  emViewType_Vmp = 2
};
PROTOBUFMSG_API bool EmViewType_IsValid(int value);
const EmViewType EmViewType_MIN = emViewType_Invalid;
const EmViewType EmViewType_MAX = emViewType_Vmp;
const int EmViewType_ARRAYSIZE = EmViewType_MAX + 1;

PROTOBUFMSG_API const ::google::protobuf::EnumDescriptor* EmViewType_descriptor();
inline const ::std::string& EmViewType_Name(EmViewType value) {
  return ::google::protobuf::internal::NameOfEnum(
    EmViewType_descriptor(), value);
}
inline bool EmViewType_Parse(
    const ::std::string& name, EmViewType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EmViewType>(
    EmViewType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace pbmsg

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pbmsg::EmViewType>() {
  return ::pbmsg::EmViewType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_enum_2eproto__INCLUDED
