#!/bin/sh

OPTION=`echo $1 | tr "A-Z" "a-z"`

cd prjlinux


echo "================ compiling regserver for ppc_x86_debug ================"
if [ "$OPTION" != "noclean" ]; then
           make -j4 -f makefile_linux_d clean;
fi

make -j4 -f makefile_linux_d 1> ../../../10-common/version/compileinfo/tpregserver_linux_d.txt 2>&1
make -j4 -f makefile_linux_d install
echo makefile_linux_d completed!


echo "================ compiling regserver for ppc_x86_release ================"
if [ "$OPTION" != "noclean" ]; then
           make -j4 -f makefile_linux_r clean;
fi

make -j4 -f makefile_linux_r 1> ../../../10-common/version/compileinfo/tpregserver_linux_r.txt 2>&1
make -j4 -f makefile_linux_r install
echo makefile_linux_r completed!




cd ..


