#!/bin/sh

cd ./prjlinux



echo "================ compiling umsmsg for linux debug ================"
make -j4 -f makefile_linux clean debug 1>umsmsg_linux_compile_debug.txt 2>&1
mv umsmsg_linux_compile_debug.txt ../../../10-common/version/compileinfo/ -f

echo "================ compiling umsmsg for linux release ================"
make -j4 -f makefile_linux clean release 1>umsmsg_linux_compile_release.txt 2>&1
mv umsmsg_linux_compile_release.txt ../../../10-common/version/compileinfo/ -f


cd ../../
