/* this file was generated by linkcmd.xdt from the gnu.targets.arm
 * package
 */
INPUT(
    /mnt/hgfs/D/code/20131028_TPS/Professional_VOB/t1-uranus/mpu2/prjlinux/test_config/package/cfg/81xxApp_xv7A.ov7A
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/video/lib/release/video.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/audio/lib/release/audio.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/lib/release/ce.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/alg/lib/release/Algorithm_noOS.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/alg/lib/release/alg.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/osal/lib/release/osal.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/ipc/dsplink/lib/release/ipc_syslink.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/osal/linux/lib/release/osal_linux_470.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/node/lib/release/node.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/osal_1_21_00_05/packages/ti/sdo/utils/loggers/lib/release/loggers.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/osal_1_21_00_05/packages/ti/sdo/xdcruntime/linux/lib/release/osal_linux_470.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/xdctools_3_20_07_86/packages/gnu/targets/arm/rtsv7A/lib/gnu.targets.arm.rtsv7A.av7A
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/linuxutils_3_21_00_02/packages/ti/sdo/linuxutils/cmem/lib/cmem.a470MV
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/framework-components_3_21_00_13/packages/ti/sdo/fc/global/lib/release/fcsettings.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/utils/xdm/lib/release/XdmUtils.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/codec-engine_3_21_00_10/packages/ti/sdo/ce/global/lib/release/cesettings.av5T
    /opt/ti-ezsdk_dm816x-evm_5_00_00_11/syslink_02_00_00_67_whole/ti/syslink/lib/syslink.a_release
)

SECTIONS {
    xdc.meta (COPY) : {KEEP(*(xdc.meta))} 

}

INSERT BEFORE .gnu.attributes

